# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: loggregator-api/v2/ingress.proto

require 'google/protobuf'

require 'loggregator-api/v2/envelope_pb'


descriptor_data = "\n loggregator-api/v2/ingress.proto\x12\x0eloggregator.v2\x1a!loggregator-api/v2/envelope.proto\"\x11\n\x0fIngressResponse\"\x15\n\x13\x42\x61tchSenderResponse\"\x0e\n\x0cSendResponse2\xf0\x01\n\x07Ingress\x12G\n\x06Sender\x12\x18.loggregator.v2.Envelope\x1a\x1f.loggregator.v2.IngressResponse\"\x00(\x01\x12U\n\x0b\x42\x61tchSender\x12\x1d.loggregator.v2.EnvelopeBatch\x1a#.loggregator.v2.BatchSenderResponse\"\x00(\x01\x12\x45\n\x04Send\x12\x1d.loggregator.v2.EnvelopeBatch\x1a\x1c.loggregator.v2.SendResponse\"\x00\x42r\n\x1forg.cloudfoundry.loggregator.v2B\x12LoggregatorIngressZ;code.cloudfoundry.org/go-loggregator/v10/rpc/loggregator_v2b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Loggregator
  module V2
    IngressResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("loggregator.v2.IngressResponse").msgclass
    BatchSenderResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("loggregator.v2.BatchSenderResponse").msgclass
    SendResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("loggregator.v2.SendResponse").msgclass
  end
end
