# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: loggregator-api/v2/ingress.proto for package 'loggregator.v2'

require 'grpc'
require 'loggregator-api/v2/ingress_pb'

module Loggregator
  module V2
    module Ingress
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'loggregator.v2.Ingress'

        rpc :Sender, stream(::Loggregator::V2::Envelope), ::Loggregator::V2::IngressResponse
        rpc :BatchSender, stream(::Loggregator::V2::EnvelopeBatch), ::Loggregator::V2::BatchSenderResponse
        rpc :Send, ::Loggregator::V2::EnvelopeBatch, ::Loggregator::V2::SendResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
